/*
 * gfx_font_data.h - generated by tools/gen_font.py.  Do not edit.
 */
#pragma once

#include "gfx_text.h"

extern const gfx_font_t gfx_font_small;
extern const gfx_font_t gfx_font_label;
extern const gfx_font_t gfx_font_value;
