#!/usr/bin/env python3
"""
Rasterise the three fonts the gauge needs into 8-bit alpha coverage masks.

Same trick as the needle sprite: the artwork is generated at build time from a
system font and shipped as a compact blob, so no font library has to run on the
device and the binary stays small.

Emitted to src/gfx_font_data.c (+ include/gfx_font_data.h):

    gfx_font_t  gfx_font_small    units, captions       ~13 px
    gfx_font_t  gfx_font_label    dial numerals         ~22 px
    gfx_font_t  gfx_font_value    big read-out          ~40 px

Each glyph is 8-bit coverage, row major, tightly cropped, with its bearing
stored so the pen can advance correctly.

Run:  python tools/gen_font.py
"""

from __future__ import annotations

import os
import sys

from PIL import Image, ImageDraw, ImageFont

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_C = os.path.join(REPO, "src", "gfx_font_data.c")
OUT_H = os.path.join(REPO, "include", "gfx_font_data.h")

# A contiguous ASCII range, so the device can index glyphs with a simple
# (c - first) and no lookup table.  Gaps (control codes, unlisted punctuation)
# simply come out blank.
CHARSET = "".join(chr(c) for c in range(0x20, 0x7F))

FONTS = [
    # name,           px,  bold
    ("gfx_font_small", 13, True),
    ("gfx_font_label", 22, True),
    ("gfx_font_value", 32, True),
]

CANDIDATES = ["seguisb.ttf", "segoeuib.ttf", "arialbd.ttf", "verdanab.ttf", "calibrib.ttf",
              "segoeui.ttf", "arial.ttf"]


def find_font() -> str:
    for n in CANDIDATES:
        p = os.path.join(r"C:\Windows\Fonts", n)
        if os.path.exists(p):
            return p
    print("no usable system font found", file=sys.stderr)
    raise SystemExit(1)


def rasterise(path: str, size: int):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    line_height = ascent + descent

    glyphs = []
    blob = bytearray()
    cap_height = 0

    for ch in CHARSET:
        # generous box, then crop to the ink
        img = Image.new("L", (size * 3, size * 3), 0)
        d = ImageDraw.Draw(img)
        d.text((size, size), ch, font=font, fill=255)
        bbox = img.getbbox()

        if bbox is None:                      # space and friends
            glyphs.append((0, 0, 0, int(round(font.getlength(ch))), len(blob), 0))
            continue

        crop = img.crop(bbox)
        w, h = crop.size
        bearing_x = bbox[0] - size             # offset from the pen origin
        # The ink top relative to the BASELINE.  PIL places the text origin on
        # the ascender line, which sits `ascent` above the baseline, so the
        # ascent has to come off again - without that every glyph is drawn one
        # ascent too low and its lower half lands outside whatever background
        # was cleared for it.
        bearing_y = bbox[1] - size - ascent
        advance = int(round(font.getlength(ch)))

        # The cap height is what text should be vertically centred on: the ink
        # height of a digit, not the line box or the ascent, both of which
        # include room the glyphs never use.
        if ch == "0":
            cap_height = h

        offset = len(blob)
        blob += crop.tobytes()
        glyphs.append((w, h, bearing_x, advance, offset, bearing_y))

    return line_height, ascent, cap_height, glyphs, blob


def main() -> int:
    path = find_font()
    print(f"font: {path}")

    parts = []
    header_glyphs = []

    for name, size, _bold in FONTS:
        line_height, ascent, cap_height, glyphs, blob = rasterise(path, size)
        total_alpha = sum(g[0] * g[1] for g in glyphs)
        print(f"  {name:<18} {size:>3}px  {len(glyphs)} glyphs, "
              f"{len(blob)} alpha bytes")
        parts.append((name, size, line_height, ascent, cap_height, glyphs, blob))
        header_glyphs.append(name)

    # ---- write the .c ------------------------------------------------------
    os.makedirs(os.path.dirname(OUT_C), exist_ok=True)
    with open(OUT_C, "w", encoding="utf-8") as f:
        f.write("/*\n"
                " * gfx_font_data.c - generated by tools/gen_font.py.  Do not edit.\n"
                " *\n"
                " * 8-bit coverage masks, row major, tightly cropped, with the\n"
                " * bearing needed to place each glyph on the pen line.\n"
                " */\n"
                '#include "gfx_font_data.h"\n\n')

        for name, size, line_height, ascent, cap_height, glyphs, blob in parts:
            f.write(f"/* {name}: {size}px, line height {line_height}, ascent {ascent}, "
                    f"cap height {cap_height} */\n")
            f.write(f"static const uint8_t {name}_alpha[] = {{\n")
            for i in range(0, len(blob), 20):
                f.write("    " + ",".join(f"0x{b:02X}" for b in blob[i:i + 20]) + ",\n")
            f.write("};\n\n")

            f.write(f"static const gfx_glyph_t {name}_glyphs[] = {{\n")
            for (w, h, bx, adv, off, by) in glyphs:
                f.write(f"    {{{w:3d},{h:3d},{bx:4d},{adv:3d},{off:6d},{by:4d}}},\n")
            f.write("};\n\n")

            f.write(f"const gfx_font_t {name} = {{\n")
            f.write(f"    .first = 0x{ord(CHARSET[0]):02X}, .count = {len(CHARSET)},\n")
            f.write(f"    .line_height = {line_height}, .ascent = {ascent}, "
                    f".cap_height = {cap_height},\n")
            f.write(f"    .glyphs = {name}_glyphs,\n")
            f.write(f"    .alpha = {name}_alpha,\n")
            f.write("};\n\n")

    # ---- write the .h ------------------------------------------------------
    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("/*\n"
                " * gfx_font_data.h - generated by tools/gen_font.py.  Do not edit.\n"
                " */\n"
                "#pragma once\n\n"
                '#include "gfx_text.h"\n\n'
                "extern const gfx_font_t gfx_font_small;\n"
                "extern const gfx_font_t gfx_font_label;\n"
                "extern const gfx_font_t gfx_font_value;\n")
        print(f"  first char 0x{ord(CHARSET[0]):02X}, {len(CHARSET)} glyphs "
              f"(0x{ord(CHARSET[0]):02X}..0x{ord(CHARSET[-1]):02X})")

    print(f"\nwrote {OUT_C}")
    print(f"wrote {OUT_H}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
